name: pipeline

channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - samtools=1.9
  - bcftools=1.9
  - bwa=0.7.17
  - sra-tools=3.0.3
  - gmap=2020.06.30
  - star=2.7.9a
  - trim-galore=0.6.6
  - python>=3.6
